version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" 
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
