[target.'cfg(all(target_arch = "wasm32", target_os = "unknown", debug_assertions))']
rustflags = [
    "--cfg",
    "erase_components",
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
]

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown", not(debug_assertions)))']
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
